### ISSUE TITLE
Failed to execute

### ISSUE THREAD

**Issue by wangeleile** [renerocksai/sublimeless_zk#1]
I tried to start the windows version and got this error message

![grafik](https://user-images.githubusercontent.com/183266/39293511-5d0b887a-4939-11e8-8306-0d47004a5080.png)

T

**Comment by renerocksai** [comment]
Hi, thanks for being brave to try it out!

This error is unfortunate.

I will work on trying to catch errors and producing a log file that gives me a clue about what went wrong.

The error you are getting indicates that the error might lie a bit deeper, maybe in the way the .EXE was put together.

Currently, I only have my Windows Laptop for building AND testing the Windows version. I will try to get a fresh, clean Windows VM. If it works on a blank Windows box, I would think that it should work on your system, too.

Will tell you when I have a new release.

Thanks again
Rene

**Comment by renerocksai** [comment]
It was **much** simpler a cause. I forgot to deploy the default settings file 🙈 . It is fixed, I updated the existing release with a new 0.2.1 zip file for windows.
