### ISSUE TITLE
Linux version - New zettel with marked text cut first letter

### ISSUE THREAD

**Issue by wangeleile** [renerocksai/sublimeless_zk#14]
When you mark a text and then press SHIFT + ENTER, not the complete Text will be copied in the new zettel field. It starts with the second letter.

**Comment by renerocksai** [comment]
Good catch!!! Will dig into this 👍

**Comment by renerocksai** [comment]
Aaaah, I found it: you had an umlaut or special character somewhere in the text before the selected text. The more umlauts you add, the more characters get cut off. Good catch 👍 

I just fixed it. This didn't make it into 0.5 though. Are you running the sources? If so, you can just pull / re-download them. Hmmm. Maybe I'll just update the released files...

**Comment by renerocksai** [comment]
I have secretly uploaded new release files :smile:
