### ISSUE TITLE
Cycling through tabs shortcuts are not usable with some keyboard layouts (ITA & FRA)

### ISSUE THREAD

**Issue by l-de-lellis** [renerocksai/sublimeless_zk#32]
Hello, this one is closely related with issue #2. 

When using an Italian or French keyboard layout the `Cycle forward through tabs (Ctrl+Shift+])` and `Cycle backward through tabs (Ctrl+Shift+[)` commands are not usable as shortcuts from the keyboard. 

With both those keyboard layouts typing the square brackets involves using the AltGr key (to access the third level symbols) and it somehow interferes with the mechanism that intercepts the other left-square-bracket-based commands.

**Comment by renerocksai** [comment]
The latest commits should fix this. Qt was consuming the characters... I verified it on a German keyboard on a Mac, where [ is Alt+5.

**Comment by renerocksai** [comment]
BTW please feel free to re-open if stuff doesn't work for you :smile:

**Comment by l-de-lellis** [comment]
After the fix everything works fine. I can enter enter both the '#' and '[' symbols using the AltGr key on the keyboard (ITA & FRA layout) and all the shortcuts are working as expected, so both #2 and #32 should be fixed. Thanks for working on this!
