### ISSUE TITLE
Implicit note creation - title not preserved [0.6, windows]

### ISSUE THREAD

**Issue by 517qf** [renerocksai/sublimeless_zk#36]
Wenn ich die "Implicit note creation" nutze, gelingt es mir nicht, den durch doppelte eckige Klammern eingefassten Titel in der Ursprungs-Notiz zu behalten, obwohl ich in der settings-Datei `insert_links_with_titles` auf `true` gesetzt habe und sl_zk neugestartet habe.

Vielleicht mache ich ja auch einen Fehler, deshalb hier eine Bildschirmaufnahme:

![slzk](https://user-images.githubusercontent.com/34541751/39696249-7662e82e-51ed-11e8-84cd-e2b84052d159.gif)

**Comment by renerocksai** [comment]
schau ich mir gleich an. wahrscheinlich hab ich was übersehen.

**Comment by renerocksai** [comment]
Is gefixt, kommt in 0.7

**Comment by renerocksai** [comment]
BTW: Dein Screen-Shot zeigt: Du könntest den [Ubuntu Mono font installieren](https://github.com/renerocksai/sublimeless_zk#installing-the-ubuntu-mono-font), den hab ich zumindest lieber...

**Comment by 517qf** [comment]
Danke für den Hinweis. Schriften sind ein schwieriges Thema. Mein momentaner Favorit ist [Fantasque Sans Mono](https://github.com/belluzj/fantasque-sans). Ich finde, diese Schrift ist kompakter und für mich etwas besser lesbar, obwohl sie recht gewöhnungsbedürftig ist ...

Für die screenshots habe ich ein neues Profil verwendet, um auszuschließen, dass eine längst vergessene von mir früher vorgenommene Einstellung dafür verantwortlich ist.

Ich schließe auch dieses issue - obwohl ich jetzt immerhin bemerkt habe, dass es dafür eigentlich das Magenta-Label gibt ...
