### ISSUE TITLE
session restore

### ISSUE THREAD

**Issue by 517qf** [renerocksai/sublimeless_zk#37]
After closing sl_zk all my tabs are gone. I would prefer if ZK would reopen all the notes I have. It would be great if there were a setting for this.

I usually have all my notes in one folder. But other people might work with many folders. Switching to a notes folder closes all tabs. When switching back to a folder some people might prefer to continue with the tabs they had open.

**Comment by renerocksai** [comment]
sounds reasonable. probably best to re-open tabs of opened folder, at startup or when opened manually. pllus a setting for that.
