### ISSUE TITLE
list of recently edited/added notes in current notes folder ?

### ISSUE THREAD

**Issue by 517qf** [renerocksai/sublimeless_zk#38]
Usually I'm interested in files I edited recently - I very often use the feature of MS Word that lists the last documents I used. At the moment I don't know how to find these. Do I miss something?

The saved search `All Notes` in the side panel seem to be sorted alphabetically so it doesn't help. Can I sort this by the files mtime?

P.S.: Thanks again for this great software.

**Comment by renerocksai** [comment]
hmmm, there is a setting to sort by note-id / title, but not by mtime.

i am contemplating whats best: a setting for sorting by mtime, a recently opened notes menu / fuzzy selector, or a command/menu to sort search results by title/id/mtime, plus reversed each. i think the last is the best --- possibly with remembering this setting ...

**Comment by 517qf** [comment]
Your last idea would be really great. Thanks for the quick reply.

**Comment by renerocksai** [comment]
done 😄 

coming soon in 0.7

![demo_mostrecent](https://user-images.githubusercontent.com/30892199/39945645-93a14f08-556b-11e8-9e8a-a79fcf249304.gif)

... and even more:

![demo_refcounts](https://user-images.githubusercontent.com/30892199/39945692-ae6504e2-556b-11e8-8199-cf76363447ec.gif)
