### ISSUE TITLE
themes: add a version of the default theme with a lower line height  (minor)

### ISSUE THREAD

**Issue by 517qf** [renerocksai/sublimeless_zk#50]
I know about the settings "line_padding_bottom" and "line_padding_top" but some new users might not find, remember or even get to the relevant section in the manual. This seems like a quick fix that hopefully doesn't inrease maintenance cost for you?

This is just a quick idea, and maybe even a bad idea: If someone reads the name "monokai - narrow" in the theme selection list he might conclude (e contrario) that this is not possible with the others. 

Anyway: close it quickly (and without commenting). Thanks.

**Comment by renerocksai** [comment]
it is calles monokai-condensed-lines 😄
