### ISSUE TITLE
change default theme to "search results" and adjust  main screenshot

### ISSUE THREAD

**Issue by 517qf** [renerocksai/sublimeless_zk#61]
That's just an idea. If you don't like it close this thread without commenting - I don't want to steal your valuable time for questions of personal preference.

dark themes are mainly popular with programers. I know that over the last year even Windows introduced a night theme - but still I think most regular users don't use a dark background. I think this makes sense: Programmers mainly use their editor so if they choose a dark theme all they see is a dark theme. Regular people or knowledge workers probably use a pdf viewer (page background is white) or a browser for a database (again: bright background). So they have to deal with a white/bight background anyway. The fact that slzk uses a dark background might make finding the right brightness harder. (I know that you can invert the background in good pdf viewers and that there are addons for a night mode in browsers but no one uses them.)

In my view the dark monokai theme doesn't integrate too well into slzk. Usually you don't close the sidebar so there will be a substantial amount of grey. Also grey is the color of the tabbar and it's background and also the color that surrounds everything. So if the main theme was also grey-ish it would be more "quiet". 

Popular, commercial markdown editors also come with a bright theme by default. Probably such commercial software uses telemetrics. If they noticed that dark themes are very popular they would have switched so that we would notice it ??? I think you can't point to the default themes for VSCode or the atom editor because they are adressed at programmers.

----

I use the search results theme which I slightly modified to increase the contrast: You already have a low contrast bright theme with solarized. I would make the headings and foreground text darker and maybe make the background slightly less grey. This would also mean less contrast between the editor area and the status bar (at least on my windows machine). This would make it more quiet (in my view better).

----

Another problem I see with the monokai theme is that it's quite opionated. It uses quite much colorful syntax highlighting. Some people like this very much, other people hate it.

**Comment by renerocksai** [comment]
I get your points. I have the following idea about your idea: Why don't you put together a good bright theme or two, and share it. I have just enabled the [Wiki](https://github.com/renerocksai/sublimeless_zk/wiki) for this repository, so you could just fire away there 😄 -- I can pull them into the next release. So, maybe start with your modified saved searches theme --- **careful with the new release. It overwrites saved_searches.json!** (because of the new search.code style). So pls make a copy.

I am all for a good bright theme, however, so far I only added themes that I liked, with a preference for dark and esoteric ones 😄 . Can you point me at a nice bright theme with a white background? Notepad++ maybe?

**Comment by renerocksai** [comment]
The Office theme is now default 😄 

<img width="1152" alt="office2" src="https://user-images.githubusercontent.com/30892199/39952622-2f602a70-559b-11e8-9555-931546dbe67a.png">

**Comment by renerocksai** [comment]
<img width="1097" alt="about2" src="https://user-images.githubusercontent.com/30892199/39952624-419f9662-559b-11e8-82cc-9f1484319b88.png">

**Comment by renerocksai** [comment]
btw thx for nudging me. the sidebar themes had a do-over, now it's even better for all themes

<img width="1041" alt="office2" src="https://user-images.githubusercontent.com/30892199/39956946-d92fe096-55ea-11e8-93a4-b86192722c49.png">

<img width="946" alt="monokai" src="https://user-images.githubusercontent.com/30892199/39956947-e0a5a02c-55ea-11e8-8561-ffeb1d452157.png">

<img width="1153" alt="solarized" src="https://user-images.githubusercontent.com/30892199/39956950-e796b646-55ea-11e8-8b6b-729db5f170e0.png">

<img width="1680" alt="c64" src="https://user-images.githubusercontent.com/30892199/39956953-ecd17f38-55ea-11e8-91e1-20f79c03635c.png">
