### ISSUE TITLE
themes heading line height determines line height for rest

### ISSUE THREAD

**Issue by 517qf** [renerocksai/sublimeless_zk#63]
The new theme and the lighter grey in the sidebar looks much better. Thank you. 

I found one problem:

I like my text to be narrow so I have "line_padding_bottom": 1 and  "line_padding_top": 1. But even though I have these settings in the office theme the line height is quite high. The only difference between the new theme and prior themes is that the headings have a size property like  `"size" : 16`. If I remove this the line height is as desired. If I add  `"size" : 16` to the heading section of a different theme I have the same problem. 

Having two different line heights in a text editor might be difficult. Even though I like big headings I prefer to have narrow lines. So maybe remove the different line heights?

**Comment by renerocksai** [comment]
I would rename the issue to theme's largest font size determines line height (for the rest). I noticed the same. Hence, in Office, I set both the paddings to 0 and it's liveable. This is something QScintilla does. So far I haven't found a way to circumvent this. It might be deeply ingrained into QScintilla, a fixed line height. Will dig deeper into this later. I'm working on instant theme switching which should make experimenting with themes more joyful.

**Comment by renerocksai** [comment]
I just checked and found it on the [Scintilla TODO List](https://www.scintilla.org/ScintillaToDo.html):

> * Different height lines based upon tallest text on the line rather than on the tallest style possible.

🙁

**Comment by 517qf** [comment]
Thanks for the quick reply.

I was afraid that this might be limitation of the underlying tool ... You could add a comment into the office theme in line 9 above line_padding_bottom - someone who wants a narrower line height will come to this setting: You could mention this issue and maybe my workaround (reduce the font size for headings).

**Comment by renerocksai** [comment]
I just found a dangerous workaround: setting both paddings to `-2` in the Office theme:

![image](https://user-images.githubusercontent.com/30892199/39962862-e087506a-565b-11e8-8205-b4679eec25f3.png)

... just causes a minimal cut-off -- you can experiment with that

**Comment by 517qf** [comment]
that's really useful. Thank you so much!
