### ISSUE TITLE
find in files: prefill with selected text (or maybe resume prior search)

### ISSUE THREAD

**Issue by 517qf** [renerocksai/sublimeless_zk#77]
When I create a new note (Ctrl+n) while I have text selected this selection is prefilled in the new title window.

Something similar would be useful for find_in_files.

At the moment there is no OR operator. I rarely need it. So my workaround is too run a search twice for both alternatives. At the moment I select the prior search string in the upper right, and use Ctrl+C, then Ctrl+Alt+F and Ctrl+v. It would be very nice if I could eliminate Ctrl+C/Ctrl+V from this process.

----

Another idea: I don't know about your preferences for context menus. I am not bothered if the context menu is quite big. So I would find it very useful if I right click selected text I would have an option to do something with the selected text like "find in files", "new note", or "open note". Maybe a submenu inside this widget where the separate commands can be hidden?

**Comment by renerocksai** [comment]
prefill with previous search: maybe, if nothing is selected. --> needs to be selected in the input field, so it can be over-written easily.
context menu: are a hassle. maybe if nothing else is there to do
