### ISSUE TITLE
Create new file with marked text use ID without seconds

### ISSUE THREAD

**Issue by wangeleile** [renerocksai/sublimeless_zk#81]
When you set    

> "seconds_in_id":

 true, and mark a text as a title for a new zettel. It doesn't use the whole Id withing the template. 
It names the file correct, but the template varialbe origin_title didn't use the correct id

**Comment by renerocksai** [comment]
origin title refers to the note you're coming from when creating the note. I will check this but without having checked I would assume the note you selected the text in didn't have seconds in its id

**Comment by renerocksai** [comment]
I can't confirm the bug. I suspect you confused `origin_title` / `origin_id` with `title` / `id`.
