### ISSUE TITLE
Deleting the file sublimeless_zk-state.json prevents slzk from starting

### ISSUE THREAD

**Issue by 517qf** [renerocksai/sublimeless_zk#83]
I removed the file sublimeless_zk-state.json and then start via cli: with the latest commits from tuesday night in ubuntu1804 (started via python(=python3) /home/user/sublimeless_zk/src/sublimeless_zk.py).

I don't think that this error is very relevant. I came to it when the startup took quite a while and I thought that removing this file might remove the obstacle. (I didn't have an actual problem - this is just a report).

```
bibfile not found: /path/to/zotero.bib

Traceback (most recent call last):
  File "/home/user/sublimeless_zk/src/sublimeless_zk.py", line 1869, in <module>
    Sublimeless_Zk().run()
  File "/home/user/sublimeless_zk/src/sublimeless_zk.py", line 543, in run
    self.open_folder(self.app_state.recent_projects[-1])
  File "/home/user/sublimeless_zk/src/sublimeless_zk.py", line 712, in open_folder
    self.save_appstate()
  File "/home/user/sublimeless_zk/src/sublimeless_zk.py", line 745, in save_appstate
    self.app_state.recently_viewed[pfolder] = {f: t for f, t in self.app_state.recently_viewed[pfolder].items() if os.path.exists(f)}
KeyError: '/home/user/zettelkasten'
```

A new file sublimeless_zk-state.json is created with this content.

`{"recent_projects": ["/home/user/zettelkasten"], "open_notes": {}, "accessed": {}}`

But it still doesn't start. When I try to start again I get the same error message

**Comment by renerocksai** [comment]
try with (i didn't test it):

```
{"recent_projects": ["/home/user/zettelkasten"], "open_notes": {"/home/user/zettelkasten": []}, "accessed": {"/home/user/zettelkasten": {}}}```

It shouldn't fall over like that but it expects to find the current project's folder in open_notes and accessed.
