### ISSUE TITLE
make ui fonts customizable

### ISSUE THREAD

**Issue by renerocksai** [renerocksai/sublimeless_zk#86]

**Comment by renerocksai** [comment]
example settings:

```json   
    "ui.font.face": "Arial",
    "ui.font.size": 14,
    "ui.tabs.font.face": "Arial",
    "ui.tabs.font.size": 14,
    "ui.statusbar.font.face": "Arial",
    "ui.statusbar.font.size": 14,
    "ui.editorinfo.font.face": "Arial",
    "ui.editorinfo.font.size": 14,
```

**Comment by patowod** [comment]
First of all, sublimeless_ZK is awesome! Thank you very much for all the work @renerocksai  — regarding the above example settings: can you give some context where exactly they should be implemented? I tried within the themes settings ("Edit current theme…") but it just won't apply the values.. I must be missing something but can't figure out what it is. Could you point me in the right direction?
