### ISSUE TITLE
Inserting citations crashes when bib-entries have an editor-field but no author-field

### ISSUE THREAD

**Issue by adamkw** [renerocksai/sublimeless_zk#92]
The "Insert Citation" feature makes the program crash, when your bib-file has entries that have an editor-field but no author-field.

**Comment by sdragulin** [comment]
Although this problem no longer appears for most entries, the app still crashes when the FIRST entry has an editor but no author. Copy-pasting the entry below one with author fixes it, but it would be nice to get it done.

**Comment by adamkw** [comment]
I wasn't able to reproduce your problem.
Could you provide a bib file that leads to a crash?

**Comment by sdragulin** [comment]
Here's an example

@book{Honenberger,
annote = {Naturalism, Pluralism, and the Human Place in the Worlds. 
Biology and Culture
are relevant both for my thesis, but also for the phil 101 course.},
editor = {Honenberger, Phillip},
title = {{Naturalism and Philosophical Anthropology. Nature, Life and the Human between Transcendental and Empirical Perspectives}}
}
@book{Scott2000,
abstract = {James Scott's Seeing Like a State provides a thorough critique of leftist variants of what he terms "high modernist" ideologies and the massive, state-directed social engineering projects they have inspired in recent centuries, particularly the twentieth. Scott pits local knowledge and pre-industrial agrarian systems against the highly centralized, monocultural, and hi tech variants favored by modernizers. Though based on an impressive and multi-disciplinary array of secondary and primary evidence, the generalized causal arguments regarding the sources of high modernism that Scott insightfully distills from his main Soviet case example often work less well for colonial or post-colonial occurrences of these projects in other areas of the globe. His cogent, at times brilliant, unpacking of the rhetoric and hubris of high modernist architects from Stalin and Julius Nyerere to Le Corbusier and Robert Moses is unfortunately not matched by an equally detailed and convincing discussion of viable alternatives to their dehumanizing, environmentally pernicious, and unsustainable visions of the future. CR - Copyright {\&}{\#}169; 2000 Oxford University Press},
archivePrefix = {arXiv},
arxivId = {arXiv:1011.1669v3},
author = {Scott, James C.},
booktitle = {Journal of Social History},
doi = {10.1353/jsh.2000.0050},
eprint = {arXiv:1011.1669v3},
isbn = {9780300078152},
issn = {0022-4529},
number = {4},
pages = {959--963},
pmid = {21063265},
title = {{Seeing Like a State}},
url = {https://academic.oup.com/jsh/article-lookup/doi/10.1353/jsh.2000.0050},
volume = {33},
year = {2000}
}

**Comment by renerocksai** [comment]
Hi,

Awesome, thanks! That should make fixing it rather easy. Will keep you
posted. Thx
-Rene
