### ISSUE TITLE
Bibliography: (no bib generated)

### ISSUE THREAD

**Issue by partnerwerk** [renerocksai/sublimeless_zk#97]
When I try to generate a bibliography I only get this output:

>[@campbell_heros_1999]: (no bib generated)

The connection to the .bib file is ok, because the program can retrieve the entries. Pandoc is installed.

I don't know what else to check.

**Comment by renerocksai** [comment]
Can you send me the corresponding section of the bibfile, pls? Aaah, and do you have pandoc installed?

**Comment by partnerwerk** [comment]
I have to apologize. After exporting the bibfile from Zotero several times and reloading it finally I got it working. So obviously pandoc was installed :-)
I cannot tell what made the change because looking at the original bibfile directly it looked fine. Also sublimeless_zk found the file to insert the shorthand entries. So I have no clue what had happened but now everything works as expected.
Thank you for your quick response! And for the app itself of course! I like Sublime but for me this is easier to work with.
